### PR TITLE
Update sync.yml

### PR DESCRIPTION
**Pull request by avahoffman**
A few more mods for AnVIL Template future syncs. 

FYI @KatherineCox

### CODE REVIEW

**Comment by KatherineCox** [comment]
@avahoffman I removed the two scripts that we were previously syncing individually since we're now syncing the whole directory

Otherwise looks good 👍

**Comment by avahoffman** [comment]
Thanks @KatherineCox !!

**Comment by avahoffman** [comment]
Revisiting @KatherineCox @cansavvy - any lingering issues with this PR?

**Comment by cansavvy** [comment]
Nah, you both know better than I what AnVIL needs so this seems fine to me.

**Review by cansavvy — APPROVED** [review]

**Review by KatherineCox — APPROVED** [review]
I think it's good to go

**Pull request merged**
