### PR TITLE
Rebase helps with render woes

### PR DESCRIPTION
**Pull request by avahoffman**
### Problem
```
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
```
[example](https://github.com/fhdsl/anvilPoll2024/actions/runs/9309089473/job/25623820837)

### Solution
I've found `--rebase` helps with this. But not sure if it's overkill. Welcome everyone's thoughts!

### CODE REVIEW

**Comment by cansavvy** [comment]
`--rebase` does feel like a lot. I'm not concerned about using it on the preview branch because it is a throw away branch, but have to think a bit more about using rebase with the main branch. Hmmm...

**Comment by cansavvy** [comment]
I think if it works I'd like to try a less drastic fix first which is what we implemented on Chris's Intro to R repo: https://github.com/fhdsl/Intro_to_R/pull/41

**Comment by cansavvy** [comment]
I think implementing to the preview branch we should definitely go ahead with! Thanks @avahoffman 

But it needs to be added to ottr-reports to be effective. (this is why the URL checker is still failing) See this PR: https://github.com/jhudsl/ottr-reports/pull/36

**Comment by avahoffman** [comment]
Done!

**Comment by cansavvy** [comment]
I think we gotta do rebase. My other less drastic solutions aren't working. I think it should be fine though? It's only for the docs folder we will be doing this. 



What I still don't understand is why this just came up as an issue and wasn't an issue previously. What's changed?

**Comment by cansavvy** [comment]
Okay I have one more try.

**Comment by cansavvy** [comment]
Never mind. Let's merge this.

**Comment by avahoffman** [comment]
@cansavvy I imagine one of the actions, perhaps checkout, has been updated or changed? 

I actually think rebase might be appropriate (and not too aggressive) here, since all the changes executed by the rendering steps should always supersede any changes on `main`. Trying to think of a situation where it could be problematic.

**Comment by cansavvy** [comment]
> @cansavvy I imagine one of the actions, perhaps checkout, has been updated or changed?
> 
> I actually think rebase might be appropriate (and not too aggressive) here, since all the changes executed by the rendering steps should always supersede any changes on `main`. Trying to think of a situation where it could be problematic.

Yeah I agree on all of this. I think you're right. Just was worried about moving to fast on something that maybe had potentially to be messy, but I think its good.

**Pull request merged**
