### PR TITLE
Add feedback form button to itcr yaml

### PR DESCRIPTION
**Pull request by cansavvy**
#### What changes are being implemented in this Pull Request?
I'm adding the feedback form to the ITCR yaml as described in #129 
This way its automatically added in a place that can be seen on each page. 

Adding this form to the Leanpub version will be a different story: https://github.com/jhudsl/DaSL_Course_Template_Leanpub/issues/34

#### What was your approach?
Added it to itcr-yaml

The form itself is a Google form. I still need to hook up the zaps in Zapier to do the downstream handling of making new issues before we can close 129. 

#### What GitHub issue does your pull request address?
#129

### CODE REVIEW

**Comment by carriewright11** [comment]
hmmm I can see about updating my embed conversion script (which works with the raw rmd files to add a line about this to each chapter)?

**Comment by carriewright11** [comment]
can you post an image of what this looks like?

**Comment by carriewright11** [comment]
I was expecting it in the footnotes section for some reason - but this makes sense too. I'm just curious how it looks. :)

**Comment by cansavvy** [comment]
Screen Shot 2021-08-23 at 3 20 15 PM

It's not the prettiest but it is functional and easy to find.

**Comment by carriewright11** [comment]
Maybe if we put it on the bottom it might look better? but maybe you tried that. I agree that it is good how easy it is to find.

**Comment by carriewright11** [comment]
also thanks for the image!

**Comment by cansavvy** [comment]
> Maybe if we put it on the bottom it might look better? but maybe you tried that. I agree that it is good how easy it is to find.

How's this? 
Screen Shot 2021-08-23 at 3 30 45 PM

**Comment by carriewright11** [comment]
Yeah, I think I like that a bit better - makes the alignment transition less intense. What do you think?

**Comment by cansavvy** [comment]
> Yeah, I think I like that a bit better - makes the alignment transition less intense. What do you think?

I have no particular preference but if you like the second one better, I'll make it that!

**Comment by carriewright11** [comment]
I can work on maybe adding an icon below the phrase or something later to see if that might make it look better (not sure what though :P) ? maybe the phrase "Provide Feedback" would be slightly more clear?

**Comment by carriewright11** [comment]
> > Yeah, I think I like that a bit better - makes the alignment transition less intense. What do you think?
> 
> I have no particular preference but if you like the second one better, I'll make it that!

thanks sounds good

**Comment by cansavvy** [comment]
> I can work on maybe adding an icon below the phrase or something later to see if that might make it look better (not sure what though :P) ? maybe the phrase "Provide Feedback" would be slightly more clear?

Because it's functional, I'm going to merge it for now. But feel free to make it prettier or change the wording later. 👍

**Pull request merged**
