### PR TITLE
Add funfetti themeing

### PR DESCRIPTION
**Pull request by avahoffman**
Switchin' up that color scheme :)

### CODE REVIEW

**Comment by carriewright11** [comment]
Looks good! I think it might still say Johns Hopkins at the bottom of the TOC

**Comment by avahoffman** [comment]
@carriewright11 Thanks! where do you see that?

**Comment by carriewright11** [comment]
> @carriewright11 Thanks! where do you see that?

it would be in the _output.yml - should probably say jhu and Fred Hutch I guess?

**Comment by carriewright11** [comment]
idk - the change in institution makes it a tad awkward

**Comment by avahoffman** [comment]
There are two `_output.yml`.. are we okay with letting the user choose?

**Comment by cansavvy** [comment]
Is this resolved yet or nah? @avahoffman

**Comment by avahoffman** [comment]
@cansavvy as long as you're cool with it!

**Comment by cansavvy** [comment]
> @cansavvy as long as you're cool with it!

LGTM!

**Pull request merged**
