### PR TITLE
Add guidance about images

### LINKED ISSUE #47: Layout more specific guidance on images
Right now we are generally linking to GoogleSlide images. Because this keeps image changes updated, we probably want to stick with this strategy (and also keeping all image together in one slide deck). 

But besides that, we shouldl determine and add to `getting_started.md`: 

- How big does the Google slide need to be? (I made one extra large 1400 x1400 pixels so the res would be better). 
- How should images be specified? (right now I've been using html img src like below because it comes out well in bookdown)
- How should width/height other parameters be specified? Would it be better in markua if this were specified as a percentage or something else? 

Example:
```
<img src=https://docs.google.com/presentation/d/1cd434bkLer_CJ04GzpsZwzeEA9gjc5Ho6QimiHPbyEg/export/png?id=1cd434bkLer_CJ04GzpsZwzeEA9gjc5Ho6QimiHPbyEg&pageid=gcdcbd8d802_0_173 width = 400 height = 400 />
```

### PR DESCRIPTION
**Pull request by cansavvy**
Two things here: 

1) Added instructions to getting_started.md about how we should add images. 
2) Added `leanbuild` to Dockerfile. 
3) Add bits about the knitr setting (See #77 ) 

Should close #47 and #77

### CODE REVIEW

**Comment by KatherineCox** [comment]
Do we have a preference on how to attach and use functions from our own build pipeline (e.g. `leanbuild`)?

1. Inline, e.g. `leanbuild::include_slide()`
2. `library(leanbuild)` at the top of each chapter
3. Attach it somewhere more global, in the bookdown/knitr/.Rprofile settings, so it's available to all chapters

Basically, explicitness/self-contained vs. convenience.

I'd vote against 2, since (like 3) it makes it non-obvious where `include_slide()` is coming from, but you still have to remember to include the `library()` call every chapter.  I've got no problem sticking with (1) so it's clear where the functions are coming from, but thought I'd toss out (3) as an option.

**Comment by cansavvy** [comment]
I like option 1 the best. Partially for the reasons you mentioned, partially just because of my own preferences.

**Comment by cansavvy** [comment]
I have a new error when trying to build locally: `r: error while loading shared libraries: libR.so: cannot open shared object file: No such file or directory` Not sure where its originating from at this point.

**Comment by cansavvy** [comment]
Now all I need to do is figure out how to properly pass the github token into the Dockerfile. I suspect I need to do something like `ENV` or something.

**Comment by cansavvy** [comment]
Turns out I don't want to use ARG or ENV with a secret: https://vsupalov.com/docker-arg-env-variable-guide/ UGH. 

I have no idea how to pass a GITHUB secret to a dockerfile securely so I can `remotes::install_github()`

**Comment by cansavvy** [comment]
In the interest of getting some of these other changes in, I've temporarily commented out the leanbuild and didactr install steps and will return to it in a next PR.

**Comment by cansavvy** [comment]
It's not the most efficient docker build: the didactr and leanbuild steps take about 17 minutes alone, but it works so we're gonna call that a win!

**Pull request merged**
