### PR TITLE
Add styler to render all workflow

### PR DESCRIPTION
**Pull request by avahoffman**
#### What changes are being implemented in this Pull Request?

This adds the code styler to the `render-all` workflow.

@cansavvy is there a reason for excluding the styler that is present in `pull-request` from `render-all`?

I just added the styler to our `render-all` for the Intro to R course, because we wanted to autostyle and check everything, but as is, OTTR and OTTR website only do that for the preview.

### CODE REVIEW

**Comment by cansavvy** [comment]
It's a little redundant to add styler to the render-all because the styler done during the preview doesn't get pushed to the preview branch, it gets pushed to the original branch (which is what gets merged) 

At least in principle this is what happens. Are you seeing unstyled code make it into `main`?

**Comment by avahoffman** [comment]
Okay, I wasn't seeing styled code committed. Maybe the render bookdown just needs to be dependent on style-code? Lemme play around with it :)

**Comment by cansavvy** [comment]
@avahoffman can you point me to an example where unstyled code was merged? As well as the pull request that preceded it?

**Comment by avahoffman** [comment]
@cansavvy I forked and created some ugly code you can see in this PR:
https://github.com/avahoffman/OTTR_Template2/pull/1
You'll see when merged, the code is still ugly:
https://github.com/avahoffman/OTTR_Template2/blob/a6dc1796e65e557cffb43d39a817a7227b51c048/index.Rmd#L29

If you take a look at some of the workflows on this repo for pull-request, you'll see this:
image
Basically, the commit is failing but the workflow still passes, hence no code styled in the PR or Render.
Let me know if you have something in mind, I won't get to this in the next few days.

**Comment by cansavvy** [comment]
Ah okay. I'll work on addressing that issue then *should* just be adding some `git config` steps.

**Comment by avahoffman** [comment]
Yes definitely need to add that. However, I was having trouble getting the commits to show up in the PR like below. I think that's important in the off chance the code is "cleaned up" in a way we don't want.

image

**Comment by cansavvy** [comment]
It's working again! All set.

**Review by cansavvy — APPROVED** [review]
Now its ready! @avahoffman do you want to double check? See the previous commits.

**Comment by avahoffman** [comment]
Worked great!! 🤩
(#550 for reference)

**Pull request merged**
