### PR TITLE
adding line about bibliography to index yml header to add references …

### PR DESCRIPTION
**Pull request by carriewright11**
…to end of ch only

#### What changes are being implemented in this Pull Request?

I am adding `bibliography: [book.bib, packages.bib]` to the index.Rmd file. This appears to be sufficient to cause the references to appear at the end of chapters. If we also want a list at the end, then we need a references.Rmd file and we need to update the _bookdown.yml to reflect this. I thought this was the reason they are showing up on my computer but not when I render with git actions, but I am not so sure now because it looks like the index.md file in the docs directory of the leadership bookdown repo still has this line. In any case we have learned more about how the references specifically show up at the end of the chapters. Again, I don't know if this will make them show up when the book is rendered with the git actions but it's a start to adding them to the template and figuring out what is going on.

#### What was your approach?

Added`bibliography: [book.bib, packages.bib]` to the index.Rmd file.

#### What GitHub issue does your pull request address?

#225 

### New Content Checklist

- [ ] New content/chapter is in an Rmd file with [this kind of format and headers](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/02-chapter_of_course.Rmd).

- [ ] New content/chapter contains [Learning Objectives and are in the correct format](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Setting-up-images-and-graphics#learning-objectives-formatting).

- [ ] [Bookdown successfully re-renders and any new content files have been added to the _bookdown.yml](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Publishing-with-Bookdown).

- [ ] Spell check runs successfully in [Github actions style-n-check](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/How-to-set-up-and-customize-GitHub-actions-robots#spell-check)).

- [ ] Any newly necessary packages that are needed have been added to the [Dockerfile and image](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Using-Docker#adding-packages-to-the-dockerfile).

- [ ] Images are in the [correct format for rendering](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Setting-up-images-and-graphics#adding-images-and-graphics-in-text).

- [ ] Every new image has [alt text and is in a Google Slide](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Setting-up-images-and-graphics#accessibility).

- [ ] Each slide is described in the notes of the slide so learners relying on a screen reader can access the content. See https://lastcallmedia.com/blog/accessible-comics for more guidance on this.

- [ ] The color palette choices of the slide are contrasted in a way that is friendly to those with color vision deficiencies.
You can check this using [Color Oracle](https://colororacle.org/).

### CODE REVIEW

**Comment by carriewright11** [comment]
I also removed author line... and one more line about links for citations. Will add a dasl favicon now...

**Comment by cansavvy** [comment]
Seems reasonable to me. Also if you'd like to test how Github actions renders something you can run this locally and check out the results: 

```
docker run \
          --mount type=bind,target=/home/rstudio,source=$PWD \
          jhudsl/course_template \
          Rscript -e "bookdown::render_book('index.Rmd')"
```

**Review by cansavvy — APPROVED** [review]
Seems reasonable to me!

**Comment by carriewright11** [comment]
> Seems reasonable to me. Also if you'd like to test how Github actions renders something you can run this locally and check out the results:
> 
> ```
> docker run \
>           --mount type=bind,target=/home/rstudio,source=$PWD \
>           jhudsl/course_template \
>           Rscript -e "bookdown::render_book('index.Rmd')"
> ```

Looks like the references disappear. However, we would need these changes to get them to appear otherwise.

**Comment by cansavvy** [comment]
> Looks like the references disappear. However, we would need these changes to get them to appear otherwise.

Like completely they disappear?

**Comment by carriewright11** [comment]
Disappear was probably the wrong word choice - they don't render at all. I didn't add the references.rmd file which would have at least made the list at the end, but I am hoping we can figure out what is different between my local rendering (without the docker image) and rendering with the docker image. Perhaps an update to one of the packages requires a new way to specify citations? or maybe it is something about a more recent change to leanbuild? not sure...

**Pull request merged**
