### PR TITLE
Update issues and advice

### LINKED ISSUE #370: using the template outside of jhudsl organization
I noticed that the starting course workflow had issues if the main branch rule happened too early - this had to be undone for everything to work properly. Perhaps we need to be more specific about the order of which automatic issues to follow when - start with secrets - let that workflow finish, then start on other automatic issue checklists.

### PR DESCRIPTION
**Pull request by cansavvy**
#### What changes are being implemented in this Pull Request?

This is a lot of little things to update for the automatic issues and other things that have slowly become outdated annotation. 

This closes #370 , #368 , #367 , #366

### CODE REVIEW

**Comment by cansavvy** [comment]
I've also incorporated some of the suggestions on #365 to the 02-chapter-of-course.Rmd and the others I'll add to the wiki.

**Comment by cansavvy** [comment]
I think this is good and the stakes for these changes are low so I'm going to merge them!

**Comment by carriewright11** [comment]
These changes look good to me! Sorry, I was already on vacation when you did these.

**Comment by cansavvy** [comment]
No worries!

**Pull request merged**
