### PR TITLE
Incorporating feedback into getting_started.md 

### LINKED ISSUE #29: docker instructions
- maybe add the link for getting a docker account
- maybe add a check that Docker installed - just running Docker
- possibly add note that they might need to update docker if they get an error (I did :P)
- add a note that it will take some time to pull the docker image
- after starting up the image with the docker run command,  I needed to run docker ps in a different terminal window (as it was still busy)
-  maybe type use username :rstudio password: what you just created to make it even more clear or maybe even an image of the sign in with rstudio typed as the username - I missed it for a second

Also, I have some images/descriptions about docker in general if you want to link out to this tutorial or use some of the material (https://github.com/carriewright11/covid_epi) for users who aren't familiar with Docker (not necessary - just a thought)

### LINKED ISSUE #41: More Testing!
### Summary 

I wrote a lot of things in `getting_started.md`. I think they make sense, but we need other people to try them! 

Whatever isn't clear we can document here and I will address and add clarity. 

@carriewright11 I think was going to do some poking around and see if the github actions, spell check, styler and etc make sense and also whether any settings need to be tweaked.

### PR DESCRIPTION
**Pull request by cansavvy**
### Summary 

@carriewright11 and @KatherineCox gave feedback on the `getting_started.md` instructions on #41 and #29 

Closes #41 and Closes #29

This PR is to address those feedback points which are: 

**Intro** 
- [x] Added resources for people unfamiliar with Git, markdown, and Rmarkdown including https://happygitwithr.com/
 
**Set up branches section**
- [x] switch "click `Add rule`" instead of `Add new rule`
- [x] need to say to check the `Require status checks to pass before merging` then say to check the `Require branches to be up to date before merging` underneath
- [x] click create and save changes to finish out the set up branches section
- [x] Tried to clear up the part about check_urls and style_n_check 

**Setting up the Docker image**
- [x] Added more explanation about what Docker is and why this is helpful
- [x] Added link to @carriewright11 's explanation about Why Docker 
- [x] Added @KatherineCox's wordings from [this comment](https://github.com/jhudsl/ITCR_Course_Template_Bookdown/issues/29#issuecomment-820098480). 

**Citations section**
- [x] Added that people can use programs like Zotero/endnote 
- [x] Changed `references.bib` file  to `book.bib` because I meant to say that. lol. 

**Github Actions section** 
- [x] Add why we don't require build-all

**Add images section**
- [x] Add that images should be placed in `resources/images/`

### CODE REVIEW

**Comment by cansavvy** [comment]
There are two items from #41 brought up by @KatherineCox that are not addressed here yet, because I'm not sure about them: 

> - What does the repo option in _bookdown.yml do, and what happens if I forget to change it? If this is important to set upfront, it'd be good to highlight it in the instructions.
> - Should LICENSE be updated to CC-BY, or should we have instructions that course developers should update the LICENSE (and leave the template under MIT)?

**Review by carriewright11 — COMMENTED** [review]
Looks great!

It seemed like I needed to check `Require status checks to pass before merging`,  before I could choose `Require branches to be up to date before merging` underneath.  So I was suggesting that we say them as separate steps:

-Check the box that says `Require status checks to pass before merging`. 
-Underneath this also check the box that says  `Require branches to be up to date before merging`.

 I first read it as  select `Require branches to be up to date before merging` without first checking `Require status checks to pass before merging` which might be confusing to other people besides me - but it might just be me :P 

Also there might be a typo here - looks like `only ran` should be `only run`: 
Note that `build-all` and `docker-build-test` are not something we recommend requiring for status checks because `docker-build-test` is only ran if there are changes to the Dockerfile and `build-all` is only run upon the acceptance and merging of a pull request.

**Comment by cansavvy** [comment]
Any other comments to address before I merge this, @carriewright11?

**Comment by carriewright11** [comment]
It looks great! I wonder if we should add how to run a docker image on windows (docker run -it --rm -v %CD%:)? or a link about that

**Comment by cansavvy** [comment]
> docker run -it --rm -v %CD%:

Good call! Will add!

**Comment by carriewright11** [comment]
Also I liked your sentence: "Particularly for courses that involve running example code, it's recommended that you use a Docker image for development to maintain software version consistency across course developers." I think it would be useful to add it back before where you link to my explanation. - good for people who might be somewhat familiar but needed an explanation as to why it would be useful in this setting.

**Review by carriewright11 — APPROVED** [review]

**Pull request merged**
