### PR TITLE
Add start to Coursera stuffs

### PR DESCRIPTION
**Pull request by cansavvy**
#### What changes are being implemented in this Pull Request?

This isn't quite working yet. It doesn't like the footer for some reason and the image file paths aren't what it wants either. Presumably it doesn't like the `leanbuild::set_knitr_image_path()` and I will need to adjust

Edit: Nope it wasn't this, it was that the css file I was referencing had file paths that were not relevant because the coursera renders have no TOC. 

### Describe your approach: 

I borrowed a script I wrote for https://github.com/AlexsLemonade/refinebio-examples/blob/staging/scripts/render-notebooks.R
But adapted it to our needs in this repo. 

The goal of the two scripts here is to output rendered htmls docs/coursera that can be linked from the github pages in Coursera. 

### Usage: 

All that needs to happen is this command: 
```
Rscript --vanilla scripts/render_all_coursera.R
```

This is related to #123

### CODE REVIEW

**Comment by cansavvy** [comment]
Only problem left to resolve (that I know of) is that the darn videos aren't rendering properly.

**Comment by cansavvy** [comment]
[coursera.zip](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/files/7085837/coursera.zip)

Here's a preview of the output. 

I'm also adding this to the render-bookdown.yml so github actions updates it automatically.

**Comment by carriewright11** [comment]
Not bad, seems like a good start. :)  I wonder why the videos aren't rendering...

**Comment by carriewright11** [comment]
if it helps we could have these rendered in the leanpub repo - to avoid messing up the bookdown version, although I see that it seems to be ok

**Comment by cansavvy** [comment]
> if it helps we could have these rendered in the leanpub repo - to avoid messing up the bookdown version, although I see that it seems to be ok

I thought about that but I think it's easier to do it here since.

**Comment by cansavvy** [comment]
> > if it helps we could have these rendered in the leanpub repo - to avoid messing up the bookdown version, although I see that it seems to be ok
> 
I thought about that but I think it's easier to do it here since we already set up GitHub pages.

**Comment by cansavvy** [comment]
I think I need to add a youtube conversion step so the url is the youtube "watch" url just like we do in leanbuild.

**Comment by cansavvy** [comment]
> I think I need to add a youtube conversion step so the url is the youtube "watch" url just like we do in leanbuild.

I might just functionalize this step in leanbuild and then use it here.

**Comment by cansavvy** [comment]
So the watch links make it take forever to load. As in I clicked on the html locally and it still is trying to load. 😱  5 minutes later.

**Comment by cansavvy** [comment]
So I think the solution here is figure out what renders reliably in an html link and just have the converting function do that.

**Comment by cansavvy** [comment]
So in the html output files from Bookdown (which youtube works) vs the Coursera script one (which youtube doesn't) they look very different. 

Whereas Coursera script output has something super long and jumbly nonsense: 
Screen Shot 2021-09-01 at 12 13 15 PM

Bookdown render has something that is more intelligible: 
```
<iframe src="https://www.youtube.com/embed/VOCYL-FNbr0" width="672" height="400px">
</iframe>
```

Just have to figure out what quirky thing is happening to make the coursera script output so jumbly.

**Comment by cansavvy** [comment]
I've been fighting with these videos and have gotten some really weird renders. It's not clear to me what voodoo bookdown is doing different to get these videos to turn out right. I might just do something kinda hacky to get it work and call it a day. Then if I figure out a more elegant solution later I can come back to it.

**Comment by cansavvy** [comment]
I've tried working with the bookdown render voodoo to just make a duplicate bookdown that doesn't have a TOC but they make it very hard to not have a TOC: 

> There are a few arguments of html_document() that have been hard-coded in gitbook() and you cannot change them: toc = TRUE (there must be a table of contents), 
From: https://bookdown.org/yihui/bookdown/html.html

And I don't know enough CSS and Java to have it edit the end product myself. Seems like it should be simple but it is not so far.  

My attempt of this strategy is on this branch: https://github.com/jhudsl/DaSL_Course_Template_Bookdown/tree/cansavvy/coursera-render-II

**Comment by cansavvy** [comment]
This is as good as it will get until #174 is resolved but I've spent so much time on this that the bandaid fix from #175 will have to do for now.

**Pull request merged**
