### PR TITLE
updating credits table

### PR DESCRIPTION
**Pull request by carriewright11**
#### What changes are being implemented in this Pull Request?

Adding template for people to delete and fill out about credits.

#### What was your approach?

I filled in a table with all possible roles and descriptions. I updated some roles... so we will need to update the [overall guideline table](https://bit.ly/course-credits-table). Or do we necessarily need both now?

### New Content Checklist

- [ ] New content/chapter is in an Rmd file with [this kind of format and headers](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/02-chapter_of_course.Rmd).

- [ ] New content/chapter contains [Learning Objectives and are in the correct format](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Setting-up-images-and-graphics#learning-objectives-formatting).

- [ ] [Bookdown successfully re-renders and any new content files have been added to the _bookdown.yml](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Publishing-with-Bookdown).

- [ ] Spell check runs successfully in [Github actions style-n-check](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/How-to-set-up-and-customize-GitHub-actions-robots#spell-check)).

- [ ] Any newly necessary packages that are needed have been added to the [Dockerfile and image](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Using-Docker#adding-packages-to-the-dockerfile).

- [ ] Images are in the [correct format for rendering](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Setting-up-images-and-graphics#adding-images-and-graphics-in-text).

- [ ] Every new image has [alt text and is in a Google Slide](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Setting-up-images-and-graphics#accessibility).

- [ ] Each slide is described in the notes of the slide so learners relying on a screen reader can access the content. See https://lastcallmedia.com/blog/accessible-comics for more guidance on this.

- [ ] The color palette choices of the slide are contrasted in a way that is friendly to those with color vision deficiencies.
You can check this using [Color Oracle](https://colororacle.org/).

### CODE REVIEW

**Comment by carriewright11** [comment]
> Re-rendered previews from the latest commit:
> 
> * See [preview of Bookdown here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/jhudsl/DaSL_Course_Template_Bookdown/preview/docs/index.html)
> * See [preview of Coursera version here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/jhudsl/DaSL_Course_Template_Bookdown/preview/docs/coursera/index.html)
> 
> _Updated at 2021-09-24 16:08:44_

These don't seem to have my current edits :(

**Comment by carriewright11** [comment]
Look OK to you @cansavvy ?

**Comment by cansavvy** [comment]
> > Re-rendered previews from the latest commit:
> 
> > 
> 
> > * See [preview of Bookdown here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/jhudsl/DaSL_Course_Template_Bookdown/preview/docs/index.html)
> 
> > * See [preview of Coursera version here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/jhudsl/DaSL_Course_Template_Bookdown/preview/docs/coursera/index.html)
> 
> > 
> 
> > _Updated at 2021-09-24 16:08:44_
> 
> 
> 
> These don't seem to have my current edits :( 

It takes time to render so you have to look at the time it was updated to know if your changes should be in there

Maybe showing the commit ID it using would be more helpful?

**Comment by carriewright11** [comment]
> > > Re-rendered previews from the latest commit:
> > 
> > 
> > > 
> > 
> > 
> > > * See [preview of Bookdown here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/jhudsl/DaSL_Course_Template_Bookdown/preview/docs/index.html)
> > 
> > 
> > > * See [preview of Coursera version here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/jhudsl/DaSL_Course_Template_Bookdown/preview/docs/coursera/index.html)
> > 
> > 
> > > 
> > 
> > 
> > > _Updated at 2021-09-24 16:08:44_
> > 
> > 
> > These don't seem to have my current edits :(
> 
> It takes time to render so you have to look at the time it was updated to know if your changes should be in there
> 
> Maybe showing the commit ID it using would be more helpful?

Yeah that would help.

**Comment by cansavvy** [comment]
I also need to fix some branch handling stuff because the changes didn't get added al the way.

**Comment by carriewright11** [comment]
> I also need to fix some branch handling stuff because the changes didn't get added al the way.

ah ok sounds good

**Pull request merged**
