### PR TITLE
Add simplified custom workflow capability 

### PR DESCRIPTION
**Pull request by avahoffman**
Adds a super simple custom workflow. Based on @cansavvy 's work and the discussion here: https://github.com/jhudsl/AnVIL_Template/pull/64

OTTR should:

- Ignore `custom-workflow.yml`
- Ensure repos downstream can add customization without OTTR syncs overwriting anything.

See the custom-workflow file here https://github.com/jhudsl/AnVIL_Template/pull/64 for an idea of what a custom workflow might entail.

### CODE REVIEW

**Comment by cansavvy** [comment]
@avahoffman  Is this working? Do we want to keep it? I lost track of what the implemented solution was over on https://github.com/jhudsl/AnVIL_Template ?

**Comment by avahoffman** [comment]
@cansavvy Let me make a few more tweaks to update things here.

Is staging up to date? Seems like a lot of changes in the diff!!

**Comment by cansavvy** [comment]
> @cansavvy Let me make a few more tweaks to update things here.
> 
> Is staging up to date? Seems like a lot of changes in the diff!!

Staging was not up to date :sad: But it should be now.

**Comment by avahoffman** [comment]
@cansavvy all good here, as long as you are good with it! I guess we want to exclude the custom workflow file from the sync right?

**Comment by cansavvy** [comment]
The more I'm thinking about it, I feel like this is more a place for a "baby ottr" and not something we want to automatically have in the main OTTR_Template. What do you think, @avahoffman ?

**Comment by avahoffman** [comment]
I am okay with whatever! I do think we need to make sure that there's an easy way to avoid overwriting workflows that are created by spinoffs. Did you have something else in mind?

**Comment by cansavvy** [comment]
> I am okay with whatever! I do think we need to make sure that there's an easy way to avoid overwriting workflows that are created by spinoffs. Did you have something else in mind?

You have to un-enroll the specific file in the sync.yml

**Pull request closed without merging**
