### PR TITLE
Add a PR template

### LINKED ISSUE #125: Create PR Template with a checklist!
From a conversation on #124 we've realized a checklist in a prominent place would be handy and I think a PR template would be just the place!

> > @carriewright11 perhaps this issue template is what you are thinking of? https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/.github/automatic-issues/set-repo-settings.md
> 
> Ah yes... maybe good to have in the getting_ready.md though? or a different checklist like pushing-to-leanpub-repo.md?

I think what we need is a PR template! And this would be the perfect spot for such a checklist!

_Originally posted by @cansavvy in https://github.com/jhudsl/DaSL_Course_Template_Bookdown/issues/124#issuecomment-900412383_

### PR DESCRIPTION
**Pull request by cansavvy**
Closes #125 !

@carriewright11 anything you think needs to be added to the checklist or template in general?

### CODE REVIEW

**Comment by carriewright11** [comment]
Looks good! hmmm maybe we should add sections for how to include videos and embedded files and then include checklist items about checking the format?

**Comment by cansavvy** [comment]
Yes sounds great! Would you be able to add that in a separate PR? That would help me to know how you do it as well!

**Comment by carriewright11** [comment]
> Looks good! hmmm maybe we should add sections for how to include videos and embedded files and then include checklist items about checking the format?

examples for videos:
<p align="center"><iframe width="560" height="315" alt = "video of Russell McClain on biases and stereotypes" src="https://www.youtube.com/embed/yiZQaE0q9BY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></p> 

```{r, fig.align="center", fig.alt = "intersectionality", echo=FALSE, out.width="100%"}
knitr::include_url("https://www.youtube.com/embed/yiZQaE0q9BY")
```

Examples for embedded files:
```{r, fig.align="center", echo=FALSE}
knitr::include_url("https://www.messiah.edu/download/downloads/id/921/Microaggressions_in_the_Classroom.pdf", height = "800px")
```
<p align="center"><iframe src="https://widgets.figshare.com/articles/5427418/embed?show_title=1" width="568" height="351" allowfullscreen frameborder="0" alt = "expectation document"></iframe></p>

**Comment by carriewright11** [comment]
> Yes sounds great! Would you be able to add that in a separate PR? That would help me to know how you do it as well!

Sure, I can do that.

**Comment by carriewright11** [comment]
> > Yes sounds great! Would you be able to add that in a separate PR? That would help me to know how you do it as well!
> 
> Sure, I can do that.

I have an appointment now so it will be in a bit...

**Comment by cansavvy** [comment]
> I have an appointment now so it will be in a bit...

No rush!

**Comment by cansavvy** [comment]
I assigned you to a separate issue for that @carriewright11 on #127  I think I will go ahead and merge this PR then assuming that there are no problems you've noticed otherwise.

**Pull request merged**
