### PR TITLE
Testing latest release and docker image

### PR DESCRIPTION
**Pull request by cansavvy**
#### What changes are being implemented in this Pull Request?
Just running a re-render and checks here to make sure things will be working.

### CODE REVIEW

**Comment by cansavvy** [comment]
Needed to add @avahoffman 's fix for the checkout@v3 related "not safe" workspace: https://github.com/jhudsl/ottr-reports/pull/16

**Comment by avahoffman** [comment]
@cansavvy I think the only other place I needed it (besides as part of ottr_reports) is right before the styler. [Example](https://github.com/jhudsl/AnVIL_Template/pull/194/commits/57fde2aca68329c02a5ac3c84f06481995fbbafd)

**Comment by cansavvy** [comment]
> @cansavvy I think the only other place I needed it (besides as part of ottr_reports) is right before the styler. [Example](https://github.com/jhudsl/AnVIL_Template/pull/194/commits/57fde2aca68329c02a5ac3c84f06481995fbbafd)

Yeah I noticed that in the next commit. 😝 I also am seeing an ottrpal bug that I'm gonna try to hot fix 🔥 

https://github.com/jhudsl/ottrpal/pull/114

**Comment by cansavvy** [comment]
Yay fixed. And now I'm going to merge and sync

**Pull request merged**
