### PR TITLE
Make preview of Bookdown in PR comment

### PR DESCRIPTION
**Pull request by cansavvy**
#### What changes are being implemented in this Pull Request?

I'm being a little scattered on this PR. Here's the three objectives that are happening: 

1) In regards to #133 - I have a new github action that renders the preview and publishes it to a comment on the PR that it updates with each push! 
2) I'm upgrading bookdown to see if this resolves the citation at end of chapters problem of #225 
3) Lastly, a minor change, I made the PR comment for the release only happen when the PR is opened (not every commit because that's annoying and unecesssary).

### CODE REVIEW

**Comment by cansavvy** [comment]
Re-rendered bookdown from this commit.
- See [preview of Bookdown here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/preview/index.html)
- See [preview of Coursera version here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/preview/index.html)

**Comment by cansavvy** [comment]
It's working!

**Comment by carriewright11** [comment]
Very cool!! Interesting that the hero image isn't previewing for the coursera version.

**Comment by cansavvy** [comment]
> Very cool!! Interesting that the hero image isn't previewing for the coursera version.

That image keeps coming in and out for me locally. That's related to the #212 I think. We should sort that out before 1.0 release.

**Comment by carriewright11** [comment]
> > Very cool!! Interesting that the hero image isn't previewing for the coursera version.
> 
> That image keeps coming in and out for me locally. That's related to the #212 I think. We should sort that out before 1.0 release.

ah ok - I see

**Comment by cansavvy** [comment]
I think this is ready! All is working!

**Pull request merged**
