### PR TITLE
Add note about running spell check manually

### PR DESCRIPTION
**Pull request by cansavvy**
@carriewright11 does this help in regards to what you were referring to about spell check?

### CODE REVIEW

**Comment by carriewright11** [comment]
yeah this looks good... I recall a checklist of steps somewhere too? does it describe the spell check ? or maybe we could add that to the getting_started.md?

**Comment by cansavvy** [comment]
@carriewright11 perhaps this issue template is what you are thinking of? https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/.github/automatic-issues/set-repo-settings.md

**Comment by carriewright11** [comment]
> @carriewright11 perhaps this issue template is what you are thinking of? https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/.github/automatic-issues/set-repo-settings.md

Ah yes... maybe good to have in the getting_ready.md though? or a different checklist like pushing-to-leanpub-repo.md?

**Comment by cansavvy** [comment]
> > @carriewright11 perhaps this issue template is what you are thinking of? https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/.github/automatic-issues/set-repo-settings.md
> 
> Ah yes... maybe good to have in the getting_ready.md though? or a different checklist like pushing-to-leanpub-repo.md?

I think what we need is a PR template! And this would be the perfect spot for such a checklist!

**Comment by cansavvy** [comment]
Checklist is being added on #126 so I think this PR can go in.

**Pull request merged**
