### PR TITLE
Trying yaml env action

### PR DESCRIPTION
**Pull request by avahoffman**
Looks like there is a solution to make yaml play nice! 😄 This code is a **test case** using the spell check GHA only.

- I largely followed the custom action [here](https://github.com/marketplace/actions/yaml-environment-action)
- I also thought it would be nice if we did a dependency using `needs`. In other words, GHA (1) must check the config before (2) the actual action/check can run. Nice example of that that [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-defining-outputs-for-a-job).

### Here's what config set to "no" looks like:
image
image

### Here's what config set to "yes" looks like. Basically just like the output we've seen thus far:
image

### Next steps

- @cansavvy do we like this approach? It might be a bit easier to maintain the R route 🙂 
- If so, I am happy to go ahead and build out the other GHA files. I will definitely need your help to make sure `delete-preview.yml`s is tied correctly to `render-preview.yml` !!

### CODE REVIEW

**Comment by cansavvy** [comment]
I really like this idea. But I think the only problem with it is that you need to have the trigger set up for it to run in the first place so it involve GHA being skipped frequently which would be confusing.

**Comment by avahoffman** [comment]
Do you mean it would be confusing for the user if an action is launched (ie, the config is checked and it says no) but the action is stopped?

**Comment by cansavvy** [comment]
> Do you mean it would be confusing for the user if an action is launched (ie, the config is checked and it says no) but the action is stopped?

Yes, that means when you open a pull request everything will be "run" but skipped and the actions log will become very cluttered. I would think pull requests would also list all of the actions whether or not they had been run.

**Comment by cansavvy** [comment]
I really like the simplicity of it though. So I'm debating about it.

**Comment by cansavvy** [comment]
Imma play around with it a second.

**Comment by avahoffman** [comment]
Yeah I definitely see your point. I wonder if it might actually be helpful for folks to know which actions they are and aren't running versus having them hidden. That way people know what their options are. 

I know it's not ideal to have one big yaml with all of the github actions, but I love the way this graph looks.. it could be really cool to have more actions mapped together this way. That could cut down on clutter.
image

**Comment by cansavvy** [comment]
I could see people seeing that the `Style and spell check R markdowns / Confirm user automation choices ` passed and misinterpreting that to mean the actual spell check passed. 

> I know it's not ideal to have one big yaml with all of the github actions, but I love the way this graph looks.. it could be really cool to have more actions mapped together this way. That could cut down on clutter.

I had this same thought and am testing out putting the PR checks all in one BIGGGG yaml. On #448

**Comment by avahoffman** [comment]
> I had this same thought and am testing out putting the PR checks all in one BIGGGG yaml. On #448

Cool! 

A potential idea: The toggle here is pretty straightforward

```
  style-n-check:
    needs: yaml-check
    runs-on: ubuntu-latest
    if: ${{needs.yaml-check.outputs.toggle == 'yes'}} 
```

Maybe we can create a simple comment akin to this one where we say that which checks were skipped? We would just need `    if: ${{needs.yaml-check.outputs.toggle == 'no'}} ` somewhere :)
image

**Comment by cansavvy** [comment]
> Maybe we can create a simple comment akin to this one where we say that which checks were skipped? We would just need ` if: ${{needs.yaml-check.outputs.toggle == 'no'}}` somewhere :)

I like this idea, but also with a little more playing around with this set up it looks like this over on #448 

And this I feel like is less ambiguous as to what is happening. It does make a huge yaml file, but on the user's front I think this is much more straightforward. Then what we have is just a `pull-request.yml` and a `render.yml` Which also addresses the problem I've been having off "too many yamls" See #345

**Comment by cansavvy** [comment]
So in conclusion, I think this solution will be very beautiful on multiple fronts! @avahoffman :tada: So I'm going to get #448 Into a better place and ask you to review it.

**Comment by cansavvy** [comment]
I think this exploration PR can be closed because #448 and #449 work on putting this into action. But I will see if @avahoffman agrees with this notion or if there's something else in this PR we need to keep.

**Comment by avahoffman** [comment]
> I think this exploration PR can be closed because #448 and #449 work on putting this into action. But I will see if @avahoffman agrees with this notion or if there's something else in this PR we need to keep.

Yes! Will close after #449 is consolidated

**Pull request closed without merging**
