### PR TITLE
Add credits information to the About.Rmd template

### LINKED ISSUE #188: Determine standard contribution labels
We want to make sure everyone is given credit for what part they played in the courses. We need to flesh out what these labels would be. 

ultimately we need to have a table that lays out specifically what contribution label means like. Something like: https://www.cell.com/pb/assets/raw/shared/guidelines/CRediT-taxonomy.pdf but for courses.

e.g. author, contributor, administration, concept generation, idea person, etc

### LINKED ISSUE #199: Add template Credits to About.Rmd file
As well as instructions in getting_started.md about how to determine and list credits for a course. This is very much related to the credit discussion on basecamp.

### PR DESCRIPTION
**Pull request by cansavvy**
#### What changes are being implemented in this Pull Request?

I'm adding info to the template which links to https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/How-to-give-credits that should give all the info authors need on how to write the credits. 

I made a public version of the credits table and published it and made a Bitly url for it: https://bit.ly/course-credits-table 

How do we feel about the: 
- Instructions at https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/How-to-give-credits
- The table at https://bit.ly/course-credits-table
- As well as the Rmd template in this PR? 

#### What GitHub issue does your pull request address?

This will close #188 
Will also close #199

### CODE REVIEW

**Comment by carriewright11** [comment]
I guess we want to remove funding agent :( sorry I didn't make that edit after our meeting with Jeff

**Comment by carriewright11** [comment]
I wonder if we should make a prepopulated one with certain people at least for jhu courses? Also maybe something similar for people who use our template to give the jhudsl/you, john, me etc credit for our work on the templates?

**Comment by carriewright11** [comment]
also I totally love your example credits :P

**Comment by cansavvy** [comment]
> I wonder if we should make a prepopulated one with certain people at least for jhu courses? Also maybe something similar for people who use our template to give the jhudsl/you, john, me etc credit for our work on the templates?

Yes, this sounds good. I'll have to find a good place for it, maybe as an html comment?

**Comment by carriewright11** [comment]
> Yes, this sounds good. I'll have to find a good place for it, maybe as an html comment?

Yeah that seems reasonable

**Comment by cansavvy** [comment]
Going to need to exclude the `About.Rmd` from spell check because of all the names.

**Comment by carriewright11** [comment]
> Going to need to exclude the `About.Rmd` from spell check because of all the names.

makes sense

**Comment by cansavvy** [comment]
I think this is all set now. Incorporated @carriewright11 's comments.

**Pull request merged**
