### PR TITLE
More styles

### PR DESCRIPTION
**Pull request by carriewright11**
#### What changes are being implemented in this Pull Request?
Added directories in the style-sets dir for GDSCN and AnVIL.  This will make it easier for people to make courses for these projects with branding associated with each.

#### What was your approach?
I cropped the logo images to get the icon part for favicons. I took descriptions about the projects from the existing courses and modified the index file. I copied the typical DASL css style file in case someone wanted to modify this specifically for each branding. The index file will use this specific css file. If someone wants more modifications to the main image I can help with that, but this will allow for the main theme colors to be changed, which is already detailed in the wiki.

#### What GitHub issue does your pull request address?

#342

### Tell potential reviewers what kind of feedback you are soliciting.
Look good to you @cansavvy @avahoffman @KatherineCox ?

Sorry I misread what you wanted previously on basecamp but looked at it again, so this should provide what you wanted. Please let me know if you would like any other changes.

### CODE REVIEW

**Comment by carriewright11** [comment]
@cansavvy the style-sets dir is  is proabably already part of the automated pull request files - but not sure

**Comment by cansavvy** [comment]
> @cansavvy the style-sets dir is is probably already part of the automated pull request files - but not sure

We can add it but I've generally avoided putting anything having to do with style to the automated pull requests because I don't want to accidentally overwrite a repo's specific style specs.

**Comment by avahoffman** [comment]
OMG this is awesome! 🤩🤩🤩

I think the only thing missing is some really simple documentation for how to do this (e.g., 1. find your style and 2. copy it over). I think it's okay for this not to be automated since it's more of a one-time enhancement/convenience rather than something breakable. But I could be persuaded otherwise :)

**Comment by carriewright11** [comment]
@avahoffman Thanks! I'm glad. Yes, we will add more to the wiki and maybe move things around for that... would an automatic issue for the checklists be helpful?

**Comment by carriewright11** [comment]
> > @cansavvy the style-sets dir is is probably already part of the automated pull request files - but not sure
> 
> We can add it but I've generally avoided putting anything having to do with style to the automated pull requests because I don't want to accidentally overwrite a repo's specific style specs.

Yeah that makes sense - I think if it is the styles-sets dir though it shouldn't overwrite anything really right? because to start implementing it people would need to copy it over to assets and the main dir anyway. But I might not be thinking this through enough.

**Comment by cansavvy** [comment]
No that's accurate, it shouldn't overwrite things if they moved the style files. But I'm not sure if we want to clutter up someone's directory. We could always include it as something that I try to put a warning about. I guess it is only one directory?

**Comment by KatherineCox** [comment]
One benefit of including it would be that downstream people would get notified when updates had been made to their style and could decide whether or not to copy them over to their book.

**Comment by cansavvy** [comment]
> One benefit of including it would be that downstream people would get notified when updates had been made to their style and could decide whether or not to copy them over to their book.

I like that. You've convinced me, let's try adding style-sets to the downstream syncs.

**Pull request merged**
