### PR TITLE
Setting up googleslides refreshing script

### PR DESCRIPTION
**Pull request by cansavvy**
### Summary 

This is a work in progress for having a script that will link up code output images to google slide images. 

Related to #46 

There are two scripts here now: 

- `scripts/google_slide_png_downloader.R` - It downloads all the PNG for a given `--slide_id`

- `scripts/google_slides_image_linker.R` - It refreshes code output images for a given `--slide_id` and stores  an image key file in the `resources` folder. This image key file stores the the image's URL, image's objectID, the slide page ID that the image is being stored on. 

It grabs images from their github URL -- the idea being that as changes are merged to `main` the github actions will run this script to refresh everything from the branch being merged (and also will call `google_slide_png_downloader.R` to download the latest files). 

When this script is ran, it will create a new slide for any code output images that don't have slides yet (according to the image key file) and then will refresh all code output images that do have slides. 

I say code output images because right now the idea is to point it to the `_bookdown_files` folder where code output images are stored, but really it would do the same action for any png file in there that you'd point it to.

### CODE REVIEW

**Comment by cansavvy** [comment]
What needs to be developed here: 

Google authorization doesn't work from Docker #49 which means that this will fail unless I pushed the `.httr-oauth` file. I don't mind doing that, but we need to think of a way for people to set up the `httr-oauth` file without it being too unwieldy. 

Right now the process is, open RStudio, run `rgoogleslides::authorize()`, follow the steps to authorize Google, then you can use the resulting `.httr-oauth`  file from a Docker container.

**Comment by cansavvy** [comment]
@muschellij2 Do you have any comments about these scripts? I'm operating on the idea that the `httr-auth` file for each repo will need to be pushed to the git repo and this will be something someone would have to set up upon starting a new google slide deck and new git repo.

**Comment by muschellij2** [comment]
The big issue is whether the .httr-oauth is encrypted or not.  If not, someone with the .httr-oauth can be you wrt Google.  It's not clear where this is addressed.

**Comment by cansavvy** [comment]
> The big issue is whether the .httr-oauth is encrypted or not. If not, someone with the .httr-oauth can be you wrt Google. It's not clear where this is addressed.

It's certainly not human-readable, but I don't know that that is the same as being well-encrypted and I am not sure how to tell how dangerous it is to have online.

**Comment by cansavvy** [comment]
This should work fine from GitHub actions, what still needs to be figured out is the authorization bits for running locally. 

This being said, I don't know how much running the scripts locally will be a necessary thing so I'm not going to hold up this PR for that. 

I will write temporary instructions for the janky way of how someone could get google auth and run this locally. 

But long term, I'll want to figure out a better solution for #49.

**Pull request merged**
