### PR TITLE
Add docker image as option

### PR DESCRIPTION
**Pull request by cansavvy**
#### What changes are being implemented in this Pull Request?

To address #476 This allows you to choose what image to render your previews and material with.

Default docker image is jhudsl/course_template:main

### CODE REVIEW

**Comment by cansavvy** [comment]
This works nicely!

**Comment by cansavvy** [comment]
@carriewright11 This will be relevant for your `ocs_guide` course. Would you be able to test it on that repository after this is merged?

**Comment by carriewright11** [comment]
> @carriewright11 This will be relevant for your `ocs_guide` course. Would you be able to test it on that repository after this is merged?

Yeah, I can do that. Does the wiki say how to specify the new docker image name? do I just replace it in `config_automation.yml`

**Comment by cansavvy** [comment]
> > @carriewright11 This will be relevant for your `ocs_guide` course. Would you be able to test it on that repository after this is merged?
> 
> Yeah, I can do that. Does the wiki say how to specify the new docker image name? do I just replace it in `config_automation.yml`

That's the idea!

**Pull request merged**
