### PR TITLE
Google analytics

### PR DESCRIPTION
**Pull request by carriewright11**
#### What changes are being implemented in this Pull Request?
Adding a template version of GA_Script.Rhtml so that people can add Google Analytics to their courses if they want to. I created a page about this for the wiki that explains how to replace the Measurement ID within the script for their respective courses and how to update the _output.yml file... as well as how to make sure the course is rerendered etc and how to check that it is working.

#### What was your approach?

I took one of my GA_Script.Rhtml files and repaced the actual Measurement ID with `{MeasurementID}` to create a template version. I also wrote a page for the wiki.

#### What GitHub issue does your pull request address?

#301 

### Tell potential reviewers what kind of feedback you are soliciting.

Work for you @cansavvy ?

### CODE REVIEW

**Comment by carriewright11** [comment]
will add the images to here: https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Google-Analytics and then put on the TOC  as a finishing touch so people can find it

**Review by cansavvy — APPROVED** [review]
This is great! Thanks for adding!

**Comment by carriewright11** [comment]
@cansavvy should I wait to merge it until we decide about the next release?

**Comment by cansavvy** [comment]
@carriewright11 No I don't think so, I think this is something good to have in the next release.

**Pull request merged**
