### PR TITLE
Attempt #2 at making manuscript folder actually delete

### PR DESCRIPTION
**Pull request by cansavvy**
#### What changes are being implemented in this Pull Request?
https://github.com/jhudsl/OTTR_Template/pull/643 didn't work. 

Next attempt is to commit the `rm -rf manuscript/` step before we committ the new files.

### CODE REVIEW

**Review by carriewright11 — COMMENTED** [review]
@cansavvy did this "old version" work?

**Comment by cansavvy** [comment]
> @cansavvy did this "old version" work?

No, this is a larger problem now with committing to main for all steps in render-all.yml. Looking into how we fix it.

**Comment by carriewright11** [comment]
> > @cansavvy did this "old version" work?
> 
> No, this is a larger problem now with committing to main for all steps in render-all.yml. Looking into how we fix it.

oh goodness - confusing...

**Comment by carriewright11** [comment]
I am happy to help more but it is hard to keep up with what you have looked at...I can meet about this tomorrow if you want.

**Comment by cansavvy** [comment]
> I am happy to help more but it is hard to keep up with what you have looked at...I can meet about this tomorrow if you want. 

I wrote this in slack but not here. A lot of the reason I thought this was failing was that my test I was using (manual workflow dispatch on the development branch) was not a good test. But when merged to main things work fine.

**Pull request merged**
