### PR TITLE
Update license

### LINKED ISSUE #296: Update License
The template currently has an [MIT License](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/LICENSE), which gets propagated to courses.  Courses generally want to be licensed under CC-BY.

On Basecamp we discussed changing the license for the template to CC-BY to make things easy for courses.

Other option, if we want to keep the template on MIT, would be to add some information in the wiki about changing your course's license as part of repository set up (might be a good idea to add that anyway).

### PR DESCRIPTION
**Pull request by KatherineCox**
Updating license from MIT to CC-BY (closes #296)

### CODE REVIEW

**Review by cansavvy — APPROVED** [review]
Seems reasonable to me!

**Comment by KatherineCox** [comment]
@cansavvy looks like it's having trouble building?

for `build-all`
```
Run actions/checkout@v2
Error: Input required and not supplied: token
```

Possibly because I forked it?  I don't know much about GitHub actions and tokens.

**Comment by cansavvy** [comment]
It's complaining about the GitHub secret, but not sure why. It shouldn't have expired, but I'm not sure why its not working. I'll try refreshing the token.

**Comment by cansavvy** [comment]
Render isn't failing on https://github.com/jhudsl/DaSL_Course_Template_Bookdown/pull/295 ? I'm going to push a fresh commit and see if that fixes it.

**Comment by cansavvy** [comment]
OH, I see its because this is a forked branch so it does not have those github secrets.

**Comment by cansavvy** [comment]
@KatherineCox We'll need to transfer over your changes to this repository's branches, or if you supply a GitHub PAT to your own forked repository that should fix it too, since you have jhudsl permissions.

**Comment by KatherineCox** [comment]
@cansavvy do I have permission to make a branch?  (is there a way I can check my permissions for a repository?)  If so, I can redo the PR from a branch and close this one.  It's easy enough to recreate, just the two changes.

**Comment by cansavvy** [comment]
@KatherineCox You should have permissions to make a PR from a new branch if you are a part of the jhudsl organization.

**Comment by KatherineCox** [comment]
Hmm, if I try to edit the README (through the GitHub GUI) it says 

> You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork KatherineCox/DaSL_Course_Template_Bookdown, so you can send a pull request.

**Comment by cansavvy** [comment]
> > You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork KatherineCox/DaSL_Course_Template_Bookdown, so you can send a pull request.

Hmm... This is perplexing. You are a part of jhudsl. It may have to do with permissions at the organization level, because I can't see anything specific to this repository. I'll look into it.

**Comment by cansavvy** [comment]
@KatherineCox In your example here, did you try to edit by making a new branch? Direct merges to main are prohibited. 

> > You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork KatherineCox/DaSL_Course_Template_Bookdown, so you can send a pull request.

**Comment by cansavvy** [comment]
> @KatherineCox In your example here, did you try to edit by making a new branch? Direct merges to main are prohibited.
> 
> > > You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork KatherineCox/DaSL_Course_Template_Bookdown, so you can send a pull request.

No, this isn't it, looks like you have different permissions to jhudsl. But if you don't mind, I would like to use this as an opportunity to see what the best way is to incorporate changes from someone who doesn't have the same permissions.

**Comment by cansavvy** [comment]
Thanks for your patience and help, @KatherineCox , this ended up being a good thing to figure out so more people can contribute in the future! Turns out the token is not needed in that particular instance, so I got rid of it so no matter what permissions levels people have they can file a PR!

**Comment by KatherineCox** [comment]
Fine by me :) Just let me know what you need me to do. And I may need some hand-holding if I need to do anything with tokens, I don't really know how they work.

**Comment by cansavvy** [comment]
Well, the preview builds properly, it just doesn't have permissions to write the comment with the links. There's a way around this that involves writing a github actions that triggers with `pull_request_target: synchronize` but I think this is a job for another day. The payoff is not worth how much its going to further obfuscate the github actions setup

**Pull request merged**
