### PR TITLE
Another Fhdsl theme update

### PR DESCRIPTION
**Pull request by avahoffman**
New theming for Hutch content.

Changes made by Amy in  
- https://github.com/fhdsl/FH_WDL101_Cromwell/pull/5
- https://github.com/fhdsl/FH_WDL101_Cromwell/pull/8
- elsewhere?

### CODE REVIEW

**Review by cansavvy — APPROVED** [review]
Looks great to me!

**Comment by carriewright11** [comment]
We have some changes to this @cansavvy  so we should wait to merge it! We worked on it for the NIH data sharing class.

**Comment by cansavvy** [comment]
> We have some changes to this @cansavvy so we should wait to merge it! We worked on it for the NIH data sharing class.

Alrighty! I'll leave it to you or @avahoffman to merge when ready then.

**Comment by avahoffman** [comment]
Thanks! Will make some changes when I have some time this week if you're okay having it dangle for a bit :)

**Comment by cansavvy** [comment]
> 

No problemo!

**Review by carriewright11 — APPROVED** [review]
Looks like everything we added :)

Thanks for adding these @avahoffman!

**Pull request merged**
